[package]
name = "choosecolor"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.russenger]
path = "../.."

[dependencies]
actix-web = "^4"
sqlx = "^0.7"

[dependencies.rusql-alchemy]
git = "https://github.com/j03-dev/rusql-alchemy"
branch = "main"
